[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
eventdotfun_program = "8BRSpxYY3FhxvZZZBvFxFG5vwPWtLeeptHor7JBPeDtm"

[programs.devnet]
eventdotfun_program = "8BRSpxYY3FhxvZZZBvFxFG5vwPWtLeeptHor7JBPeDtm"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/fixtures/mpl_core.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "./keys/turbin3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
